services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
