"""Init

Revision ID: 3b458e63e0b7
Revises: 232d9fbecb59
Create Date: 2024-08-31 11:54:30.642825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b458e63e0b7'
down_revision: Union[str, None] = '232d9fbecb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('qr_code', sa.Text(), nullable=True))
    op.drop_column('posts', 'foto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('foto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'qr_code')
    op.drop_column('posts', 'url')
    # ### end Alembic commands ###
